"""fix relationships

Revision ID: 02955d5a20c3
Revises: 5be13058dcde
Create Date: 2024-10-26 15:55:13.413161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02955d5a20c3'
down_revision: Union[str, None] = '5be13058dcde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_one_id', sa.Integer(), nullable=True),
    sa.Column('participant_two_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['participant_one_id'], ['User.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_two_id'], ['User.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Chat_id'), 'Chat', ['id'], unique=False)
    op.add_column('Message', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Message', 'Chat', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.drop_column('Message', 'chat_id')
    op.drop_index(op.f('ix_Chat_id'), table_name='Chat')
    op.drop_table('Chat')
    # ### end Alembic commands ###
