"""create user table

Revision ID: d02794d6bc1e
Revises: 9ea7cf9e26dc
Create Date: 2024-10-23 23:33:24.451213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02794d6bc1e'
down_revision: Union[str, None] = '9ea7cf9e26dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('User', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('User', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_verified')
    op.drop_column('User', 'is_superuser')
    op.drop_column('User', 'is_active')
    # ### end Alembic commands ###
